### ISSUE TITLE
error invoking show when using aurelia-i18n with webpack

### ISSUE THREAD

**Issue by fabioluz** [aurelia/binding#376]
I'm not sure if this issue is related to aurelia binding, templating or i18n. Sorry if I posted it in the wrong repository.

Considering that I'm using the latest version of es2016-skeletonproject-webpack, If I install the `aurelia-i18n` following the instructions in the docs, I can't use `show.bind` anymore.

For example:
1. Download skeleton project
2. Install packages `npm install`
3. Install aurelia-i18n `npm install aurelia-i18n --save`

Let's say this is my main.js:

```
bootstrap(function(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-i18n', (instance) => {
      // register backend plugin
      instance.i18next.use(XHR);

      // adapt options to your needs (see http://i18next.com/docs/options/)
      instance.setup({
        backend: {                                  // <-- configure backend settings
          loadPath: '/locales/{{lng}}/{{ns}}.json', // <-- XHR settings for where to get the files from
        },
        lng : 'de',
        attributes : ['t','i18n'],
        fallbackLng : 'en',
        debug : false
      });
    });

  aurelia.start().then(() => aurelia.setRoot('app', document.body));
});
```

This line `import {I18N} from 'aurelia-i18n';` is not necessary, but it's listed in the docs.

Now, if I use a `show.bind`, like this:

```
<div class="page-host" show.bind="isVisible">
  <router-view></router-view>
</div>
```

I get the following error:

```
Unhandled rejection Error: Error invoking Show. Check the inner error for details.
------------------------------------------------
inner error: Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
```

This error doesn't happen if I remove the `import {I18N} from 'aurelia-i18n';`. The plugin still works, however. 

This works normally with SystemJS.

**Comment by EisenbergEffect** [comment]
Can you make sure you aren't somehow getting multiple different versions of libraries loading at runtime?

**Comment by sylvain-hamel** [comment]
At [this line](https://github.com/aurelia/i18n/blob/master/dist/aurelia-i18n.js#L520) the code refers to `Element`. `i18n` may have an undeclared dependency on `aurelia-pal/aurelia-pal-browser`. 

Try this:

Add those two lines before your first import to see if it fixes the problem:

```
import {initialize} from 'aurelia-pal-browser';
initialize();
```

**Comment by fabioluz** [comment]
@EisenbergEffect  Thank you for the response.

I've just downloaded the latest skeleton project again (1.0.0-beta.1.2.2). Then, I made the following changes, in that specific order:

Installed the packages
- npm install
- npm install aurelia-i18n --save
- npm install i18next-xhr-backend --save

Included the submodules
```
new AureliaWebpackPlugin({
  includeSubModules: [
    { moduleId: "aurelia-i18n" }
  ]
})
```
Configured the main.js

```
var Promise = require('bluebird'); // Promise polyfill for IE11
import {bootstrap} from 'aurelia-bootstrapper-webpack';
import {I18N} from 'aurelia-i18n';
import XHR from 'i18next-xhr-backend';

import '../node_modules/bootstrap/dist/css/bootstrap.css';
import '../node_modules/font-awesome/css/font-awesome.css';
import '../styles/styles.css';

bootstrap(function(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-i18n', (instance) => {
      // register backend plugin
      instance.i18next.use(XHR);

      // adapt options to your needs (see http://i18next.com/docs/options/)
      instance.setup({
        backend: {                                  // <-- configure backend settings
          loadPath: '/locales/{{lng}}/{{ns}}.json', // <-- XHR settings for where to get the files from
        },
        lng : 'de',
        attributes : ['t','i18n'],
        fallbackLng : 'en',
        debug : false
      });
    });

  aurelia.start().then(() => aurelia.setRoot('app', document.body));
});

```

Added a show.bind expression

```
<div class="page-host" show.bind="isVisible">
    <router-view></router-view>
  </div>

export class App {
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { route: ['', 'welcome'], name: 'welcome',      moduleId: 'welcome',      nav: true, title: 'Welcome' },
      { route: 'users',         name: 'users',        moduleId: 'users',        nav: true, title: 'Github Users' },
      { route: 'child-router',  name: 'child-router', moduleId: 'child-router', nav: true, title: 'Child Router' }
    ]);

    this.router = router;
  }

  isVisible = true;
}

```
Then
`npm run dev`

The error still occurs. That's my packages.json:

```
{
  "name": "aurelia-skeleton-navigation-webpack",
  "version": "1.0.0-beta.1.2.2",
  "description": "A starter kit for building a standard navigation-style app with Aurelia and webpack.",
  "main": "index.js",
  "scripts": {
    "dev": "webpack-dev-server --config webpack.config.js --hot --inline --progress --devtool eval",
    "build": "webpack --config webpack.config.js --progress --profile",
    "prod": "webpack -p --config webpack.prod.config.js --progress --devtool source-map",
    "test": "karma start",
    "webdriver:update": "./node_modules/.bin/webdriver-manager update",
    "webdriver:start": "./node_modules/.bin/webdriver-manager start",
    "pree2e": "npm run webdriver:update -- --standalone",
    "e2e": "./node_modules/.bin/protractor"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/aurelia/skeleton-navigation.git"
  },
  "keywords": [
    "aurelia",
    "skeleton",
    "navigation",
    "webpack"
  ],
  "author": "Martijn Boland",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/aurelia/skeleton-navigation/issues"
  },
  "homepage": "https://github.com/aurelia/skeleton-navigation#readme",
  "dependencies": {
    "aurelia-bootstrapper-webpack": "^1.0.0-beta.1.0.0",
    "aurelia-event-aggregator": "^1.0.0-beta.1.1.1",
    "aurelia-fetch-client": "^1.0.0-beta.1.1.0",
    "aurelia-framework": "^1.0.0-beta.1.1.3",
    "aurelia-history-browser": "^1.0.0-beta.1.1.2",
    "aurelia-i18n": "^0.5.2",
    "aurelia-logging-console": "^1.0.0-beta.1.1.4",
    "aurelia-pal-browser": "^1.0.0-beta.1.1.4",
    "aurelia-polyfills": "^1.0.0-beta.1.0.0",
    "aurelia-router": "^1.0.0-beta.1.1.1",
    "aurelia-templating-binding": "^1.0.0-beta.1.1.1",
    "aurelia-templating-resources": "^1.0.0-beta.1.1.1",
    "aurelia-templating-router": "^1.0.0-beta.1.1.1",
    "bluebird": "^3.3.4",
    "bootstrap": "^3.3.6",
    "font-awesome": "^4.5.0",
    "i18next-xhr-backend": "^0.5.3",
    "isomorphic-fetch": "^2.2.1"
  },
  "devDependencies": {
    "aurelia-tools": "^0.1.18",
    "aurelia-webpack-plugin": "^1.0.0-beta.1.0.0",
    "babel-core": "^6.7.2",
    "babel-eslint": "^5.0.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-stage-1": "^6.5.0",
    "css-loader": "^0.23.1",
    "eslint": "^1.10.3",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.9.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.21",
    "karma-babel-preprocessor": "^6.0.1",
    "karma-chrome-launcher": "^0.2.2",
    "karma-jasmine": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "protractor": "^3.2.1",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "wallaby-webpack": "0.0.21",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1"
  }
}
```

Am I doing something wrong?

@sylvain-hamel I tried what you said. Didn't work either :/

**Comment by jdanyow** [comment]
@fabioluz did you get this sorted out?  This error isn't a binding thing: `key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?`

**Comment by fabioluz** [comment]
As I said, I wasn't sure if this is related to aurelia-binding. I posted it here because the error only happens when I use `show.bind`.

A new Aurelia version has been released since I posted the issue. I'll try to reproduce this error using the latest skeleton.

**Comment by fabioluz** [comment]
@jdanyow This error still happens in the latest skeleton-es2016-webpack. 

Here's an example https://mega.nz/#!1FEyFT6D!PDTuXrWTJ66_meyp4mxeJ_0aBdlK-9RfR0ta9bVDfjM

**Comment by suneelv** [comment]
I had a very similar problem. Whenever I added a compose element, I am getting this error

```
 Error invoking Compose. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
Inner Error Stack:
Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at Container.get (http://localhost:3000/bundle.js:45319:14)
    at Container.elementContainerGet [as get] (http://localhost:3000/bundle.js:36221:16)
    at Object.invokeWithDynamicDependencies (http://localhost:3000/bundle.js:45150:26)
    at InvocationHandler.invoke (http://localhost:3000/bundle.js:45139:167)
    at Container.invoke (http://localhost:3000/bundle.js:45403:24)
    at ProviderResolver.get (http://localhost:3000/bundle.js:36166:73)
    at Container.get (http://localhost:3000/bundle.js:45340:22)
    at Container.elementContainerGet [as get] (http://localhost:3000/bundle.js:36221:16)
    at HtmlBehaviorResource.create (http://localhost:3000/bundle.js:38073:57)
    at applyInstructions (http://localhost:3000/bundle.js:36299:32)
    at ViewFactory.create (http://localhost:3000/bundle.js:36521:8)
    at HtmlBehaviorResource.create (http://localhost:3000/bundle.js:38085:40)
    at http://localhost:3000/bundle.js:38470:17
End Inner Error Stack
------------------------------------------------

    at Container.get (http://localhost:3000/bundle.js:45319:14)
    at Container.elementContainerGet [as get] (http://localhost:3000/bundle.js:36221:16)
    at Object.invokeWithDynamicDependencies (http://localhost:3000/bundle.js:45150:26)
    at InvocationHandler.invoke (http://localhost:3000/bundle.js:45139:167)
    at Container.invoke (http://localhost:3000/bundle.js:45403:24)
    at ProviderResolver.get (http://localhost:3000/bundle.js:36166:73)
    at Container.get (http://localhost:3000/bundle.js:45340:22)
    at Container.elementContainerGet [as get] (http://localhost:3000/bundle.js:36221:16)
    at HtmlBehaviorResource.create (http://localhost:3000/bundle.js:38073:57)
    at applyInstructions (http://localhost:3000/bundle.js:36299:32)
    at ViewFactory.create (http://localhost:3000/bundle.js:36521:8)
    at HtmlBehaviorResource.create (http://localhost:3000/bundle.js:38085:40)
    at http://localhost:3000/bundle.js:38470:17
End Inner Error Stack
------------------------------------------------

    at new AggregateError (http://localhost:3000/bundle.js:28509:12)
    at Container.invoke (http://localhost:3000/bundle.js:45405:14)
    at ProviderResolver.get (http://localhost:3000/bundle.js:36166:73)
    at Container.get (http://localhost:3000/bundle.js:45340:22)
    at Container.elementContainerGet [as get] (http://localhost:3000/bundle.js:36221:16)
    at HtmlBehaviorResource.create (http://localhost:3000/bundle.js:38073:57)
    at applyInstructions (http://localhost:3000/bundle.js:36299:32)
    at ViewFactory.create (http://localhost:3000/bundle.js:36521:8)
    at HtmlBehaviorResource.create (http://localhost:3000/bundle.js:38085:40)
    at http://localhost:3000/bundle.js:38470:17
```

After struggling for hours @fabioluz solution on gitter finally fixed the issue
I have removed import {I18N} from my main file and now everything seems to be working fine.

**Comment by EisenbergEffect** [comment]
This is very odd. @zewa666 and @niieani Can you look into this?

**Comment by niieani** [comment]
I used to get this error when aurelia-pal wasn't initialized **before** Aurelia was loaded. Otherwise things seemed to work but when DI was injecting `Element`, it was undefined, cause that was coming from PAL.
I'll look into this. We should probably change the way aurelia-pal keeps references to its elements, so it's more robust (i.e. would work even if the code is evaluated in the wrong order).

**Comment by niieani** [comment]
@EisenbergEffect here's what I mean:

https://github.com/aurelia/templating-resources/blob/master/src/compose.js#L14

If `aurelia-pal-browser` is not initialized before (in this case) `aurelia-templating-resources` is loaded by the browser, the value of `DOM.Element` which is being injected here, will be `undefined`, because `aurelia-pal` [defines it as `{}`](https://github.com/aurelia/pal/blob/master/src/index.js#L308). 

This is not a problem for the unbundled JSPM, but when the code is bundled (like with Webpack) it's hard to predict which parts of the code will be evaluated by the browser in which order -- for this reason I've made a workaround in the webpack skeletons to always bundle **aurelia-pal** and **aurelia-pal-browser** into a separate bundle that always **loads before** any of the other Aurelia modules, to ensure Pal is initialized. Instead injecting properties of `DOM` directly (properties which don't have to exist when the decorator is evaluated), we should find a safer method to inject properties of PAL - in a context that is not evaluated at the time the code is loaded (as is the case with decorators or static properties).

Hope that's clear.

**Comment by EisenbergEffect** [comment]
To me, this seems like a bug in Webpack since it's not enforcing the load order indicated by the module imports.

**Comment by niieani** [comment]
@EisenbergEffect As you are aware, there is currently no formal standard that explains how to load modules in the browser, or one which would indicate a "correct load order" for the modules. Webpack caches all the modules contained in a given bundle during its **load time**, which means any side-effects, such as class declarations, static declarations, variable declarations and decorators are evaluated in that phase - during bundle load time. I don't know how JSPM / SystemJS does it, but I guess it delays it until the first invocation of the first file that imports it, hence the problem isn't occurring there. 

But I would argue this is not a "Webpack bug", but a design decision that might change at any time -- as much for SystemJS's bundling system as for Webpack, so we should not depend on it until there is a standardized way to load ES2015 modules in the browser that we could refer to. We should either keep enforcing PAL initialization in a separate bundle, as I've currently done in the Webpack Skeleton, or have a different solution for declaring / using side effects of external modules that need an initialization process.

Finally, since we haven't actually solved @fabioluz's problem, I would ask you to reopen this until we do. As long as _i18n_ is contained in the proper bundle, the root of the problem might be caused by something else, and I will investigate in due time.

**Comment by EisenbergEffect** [comment]
Happy to re-open this issue, but I don't think you are correct with respect to modules. The semantics of the module system are defined by ECMA. It's the loader itself that has an unfinished spec.

**Comment by niieani** [comment]
@EisenbergEffect yes, and the issue is with modules, it's about how the modules are loaded, which will be in the loader spec.

**Comment by doktordirk** [comment]
seems to be the same issue as mine

**Comment by EisenbergEffect** [comment]
Regardless, it is a requirement that the platform be loaded before the framework. So, we need to setup webpack in whatever way will ensure that.

**Comment by niieani** [comment]
OK. I'll look into this issue then.

**Comment by doktordirk** [comment]
nay news?

**Comment by niieani** [comment]
I was wrong about: https://github.com/aurelia/binding/issues/376#issuecomment-230814720. 
It was caused by a bug in aurelia-bootstrapper-webpack. I believe this should now be fixed in https://github.com/aurelia/bootstrapper-webpack/commit/54d385c58fcd570f197b65ddc84d50bdb4dbca9b.

**Comment by RomkeVdMeulen** [comment]
I'm running into a similar problem on a JSPM / SystemJS project. I've updated to latest versions, including bootstrapper 2.0.1, but the problem persists. When adding `<div slot="x">` anywhere, I get this error:

```
aurelia.js:16441 Uncaught Error: Error invoking SlotCustomAttribute. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
Inner Error Stack:
Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at validateKey (http://localhost:8080/myproject/frontend/bundles/aurelia.js:6664:13)
    at Container.get (http://localhost:8080/myproject/frontend/bundles/aurelia.js:6810:7)
    at Container.elementContainerGet [as get] (http://localhost:8080/myproject/frontend/bundles/aurelia.js:8642:17)
    at Object.invoke (http://localhost:8080/myproject/frontend/bundles/aurelia.js:6700:33)
    at InvocationHandler.invoke (http://localhost:8080/myproject/frontend/bundles/aurelia.js:6678:168)
    at Container.invoke (http://localhost:8080/myproject/frontend/bundles/aurelia.js:6873:25)
    at ProviderResolver.get (http://localhost:8080/myproject/frontend/bundles/aurelia.js:8601:74)
    at Container.get (http://localhost:8080/myproject/frontend/bundles/aurelia.js:6828:23)
    at Container.elementContainerGet [as get] (http://localhost:8080/myproject/frontend/bundles/aurelia.js:8642:17)
    at HtmlBehaviorResource.create (http://localhost:8080/myproject/frontend/bundles/aurelia.js:10198:58)
End Inner Error Stack
```

If I go into the source and replace `DOM.Element` with `Element` in the `SlotCustomAttribute` injection, named slots function as expected.

I suspect the error is somehow related to this bug. Should I create a new issue for this?

**Comment by omnipresentminded** [comment]
I am running into the same issue with show.bind on system js. We began to have the issue when we updated. Aurelia-pal when from 1.1.1 to 1.2.0. Aurelia-dependency-injection went from 1.2.0 to 1.2.1. All else stayed the same.  The issue occurs even un-bundled.

Using a css class got us around the issue for now. 

Broken with show.bind
 `<div class="ppc-progress" show.bind="!isUpdating">
                                <div class="ppc-progress-fill"></div>
                            </div>

                            <div class="loading-container" show.bind="isUpdating">
                                <div class="circle2"></div>
                                <div class="circle1"></div>
                                <div class="dot"></div>
                            </div>
                            <div class="ppc-percents">
                                <div class="pcc-percents-wrapper" show.bind="!isUpdating">
                                    <span show.bind="skus.length >= 1">%</span>
                                </div>
                            </div>`

Works with css 
         `               <div class="ppc-progress ${isUpdating ? 'nodisplay':''}">
                                <div class="ppc-progress-fill"></div>
                            </div>

                            <div class="loading-container ${!isUpdating ? 'nodisplay':''}">
                                <div class="circle2"></div>
                                <div class="circle1"></div>
                                <div class="dot"></div>
                            </div>
                            <div class="ppc-percents ">
                                <div class="pcc-percents-wrapper ${isUpdating ? 'nodisplay':''}">
                                    <span class="${skus.length < 1 ? 'nodisplay':''}">%</span>
                                </div>
                            </div>`

**Comment by StrahilKazlachev** [comment]
@omnipresentminded @RomkeVdMeulen Since you are saying the problem occurred after updates see aurelia/templating-resources#267 for more info.

**Comment by RomkeVdMeulen** [comment]
@StrahilKazlachev To clarify: I tested on the latest versions to reproduce, but the problem was already occurring with version 1.0.0 of templating, templating-resources and dependency-injection.

I'll go watch the linked issue.

**Comment by StrahilKazlachev** [comment]
@RomkeVdMeulen Your problem may be unrelated to the DI issue, but the circumstances and error seem similar.

**Comment by RomkeVdMeulen** [comment]
Well, the fix for metadata was rolled out, but the problem persists. I'll file a new bug for it.

**Comment by niieani** [comment]
Should be fixed by https://github.com/aurelia/skeleton-navigation/pull/714

**Comment by RomkeVdMeulen** [comment]
@niieani Perhaps you could lend your wisdom to aurelia/pal-browser/#17 as well? It's a similar problem to this, also occurring in the JASON flavour.

**Comment by niieani** [comment]
@RomkeVdMeulen I'm sorry but I'm not using JSPM.

**Comment by bdefore** [comment]
i ran into this error when using a vendor chunk with webpack. the following libraries were or weren't able to be chunked without triggering it (commented out ones could not be):

```
      'algoliasearch',
      'aurelia-animator-css',
      'aurelia-binding',
      'aurelia-bootstrapper',
      'aurelia-configuration',
      // 'aurelia-i18n',
      'aurelia-framework',
      'aurelia-fetch-client',
      'aurelia-loader-webpack',
      'aurelia-pal-browser',
      'aurelia-polyfills',
      'aurelia-router',
      // 'aurelia-templating',
      // 'aurelia-templating-resources',
      'aurelia-validation',
```

**Comment by migajek** [comment]
what is the fix here actually? I'm also having the case where DOM.Element (first dependency for the TCustomAttribute) is undefined 
I have no idea how to deal with that

**Comment by bigopon** [comment]
I think I'd agree with @niieani . Though platform specific code must run before all else otherwise `DOM.Element` will often be resolved before its value gets assigned by specific PAL code, which is `undefined`. This is not always obvious why it wouldn't work, and this could be sometimes barrier for newcomer. Illustrated via following block for anyone wanting to know what happened:

```js
class T {
  // will be undefined if PAL code was not run before this
  static inject = [DOM.Element]
  
  // will be fine, regardless the PAL code evaluation order
  static inject() {
    return [DOM.Element];
  }
}
```

Fix at https://github.com/aurelia/i18n/pull/266

@EisenbergEffect

**Comment by migajek** [comment]
to be honest, I still don't know what is wrong with my initialization order... but the changes in your PR seem to fix the problem for me

**Comment by zewa666** [comment]
mentioned PR has been merged. That was clearly an oversight by me, as most other parts of the I18N plugin do request injects exactly as proposed. It's merged and should be released soon

**Comment by bigopon** [comment]
We still have this https://github.com/aurelia/templating/blob/master/src/shadow-dom.js#L7 that still occasionally destroys folks' tests, would be awesome if someone can PR to fix it 😄

**Comment by migajek** [comment]
just for the records ... should I assume as a rule of thumb anytime I inject `DOM.Element` I should use `inject` class method instead of property?

**Comment by doktordirk** [comment]
incidentally i just had PRed a fix for autoinject which would prevent that issue as i see it
https://github.com/aurelia/dependency-injection/pull/162

**Comment by ielcoro** [comment]
As @HIRANO-Satoshi already said, since this was merged, autoinject no longer Works, as it calls injects like an array variable instead of calling it as a function.

**Comment by doktordirk** [comment]
Autoject shouldn.t call anything. Whole point is to get the types for the DI from  the constructor. Anything inherited should be ignored. similarly using autoinject together with an own inject array or function doesn.t make any sense.
