### ISSUE TITLE
Connected bindings not updated on same TaskQueue cycle

### ISSUE THREAD

**Issue by CasiOo** [aurelia/binding#479]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

* **OS:**
Windows 10
Windows 8

* **Browser:**
Chrome 52.0.2743.116
Opera 39.0.2256.48

* **Language:**
all

**Current behavior:**
Two-way bindings on a custom element don't get updated before the `change` event handler is invoked. Bindables on the local custom element get updated before the change event, but any binding to the bindables do not get updated in the same cycle.

Current behavior shown here. Read the console messages: https://gist.run/?id=2f42ade7554b9249a5d7777f3961d1c3

Change the dropdown value. The console prints:
Dropdown changeEvent: 2
App filteredGroupChangeEvent: <blank>

Hopefully the gist makes more sense than my written issue :)

**Expected/desired behavior:**
Console prints:
Dropdown changeEvent: 2
App filteredGroupChangeEvent: 2

* **What is the expected behavior?**
It looks like any custom element bindings are put on the TaskQueue as micro tasks. It is possible for the programmer to wrap his code in a micro task, but I'm not sure this is the desired behavior.

* **What is the motivation / use case for changing the behavior?**
Avoid any confusing as to why the bindings don't update at the same time, and remove the need for the task queue as a developer.

**Comment by MiiCode2** [comment]
Just for your info, I'm running OSX 10.10.2 Yosemite and I have tried your gist run on two different computers one with Chrome 51.0.2704.103 canary and another with Chrome 54.0.2824.0 canary.

Your gist runs and produces the desired output as follows:

Dropdown changeEvent: 2
App filteredGroupChangeEvent: 2

So there might be something else going here.  I also tried the code in the discussions and I received the desired results with or without the micro task.

**Comment by CasiOo** [comment]
Thank you @MiiCode2. Updated the issue with OS and browser versions.

@minro was the one posting the issue on gitter. I don't know what browser/os he's using, but he should be getting the same output as I.

**Comment by minro** [comment]
I'm getting the same output as you are, both in Chrome latest version on windows and iE where my target is 11 (I can't run gists in iE but my own code (which is the basis of @CasiOo's example) produces the same result as stated for Chrome).

**Comment by minro** [comment]
If the TaskQueue behavior is considered correct, I solved the issue by making the select value observable:

.html
`
<dropdown selection.two-way="filteredGroup" default="${'groupfilter' | t}" options.bind="groups"></dropdown>
`

.ts
`
@observable filteredGroup: string;
private filteredGroupChanged() {...}
`

which means there are no other changes in the custom element apart from removing the change.delegate call.

**Comment by EisenbergEffect** [comment]
Should now be fixed.

**Comment by Mobe91** [comment]
I am still facing this issue:
https://gist.run/?id=f1f10a46ea30ba9c4bcfef05755828a2
