### ISSUE TITLE
Debounce not working as expected (saving first value change instead of last one)

### ISSUE THREAD

**Issue by Tarpsvo** [aurelia/binding#485]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.4.7
- **NPM Version:**
  3.10.6
- **JSPM OR Webpack AND Version**
  2.1.0-beta.21
- **Browser:**
  Chrome
- **Language:**
  ESNext

**Current behavior:**
The binding is as follows: `if.bind="value > 0 & debounce:1000"`
When value changes rapidly to 1 and then 0, and the debounce activates after 1 second, it will still use 1 as its value and the check will pass, even though `value` is  0.

**Expected/desired behavior:**
Expected result is to use the value that `value` is at the time of the debounce activation.

https://gist.run/?id=b0e5fd3fbaad39eb2b8b8fa6482d2589

**Comment by jdanyow** [comment]
https://gist.run/?id=065b5e45ea473fac03d98c85945739cf

**Comment by Tarpsvo** [comment]
Made an easier to read gist (also updated original post).

https://gist.run/?id=b0e5fd3fbaad39eb2b8b8fa6482d2589

**Comment by Tarpsvo** [comment]
@jsobell Made the following discovery:

> https://gist.run/?id=765c24121f18196f73366f3fa4558fac
> This is the problem you're seeing, and it's unrelated to the visual stuff
> It should only be retaining the final state, and dropping the intermediate changes, but it looks like it's retaining the first change and dropping the others

**Comment by jsobell** [comment]
It's actually a bit more tricky than I thought.
Something related to the binding process (something Promise related?) prevents subsequent bindings being processed until the first has completed.
So if we make a call to the original binding (with the same 'old' value) the debounce problem is avoided, as shown in this Gist.run:
[https://gist.run/?id=4cfe4f76ee753b6660ad13ba60db8ddd](https://gist.run/?id=4cfe4f76ee753b6660ad13ba60db8ddd)
Obviously this is not ideal, but we need some way to inform the binding instance to no longer wait for a result, but to essentially cancel the current wait and we will initiate a new one when we're ready.
I'll ask @jdanyow about it when he wakes up.

**Comment by jsobell** [comment]
This only appears to affect checkbox bindings, as the effect is not observed on string inputs

**Comment by jdanyow** [comment]
@Tarpsvo I re-tested this- it looks like it might be working like you expect now:

https://gist.run/?id=065b5e45ea473fac03d98c85945739cf

I believe this might have been fixed by https://github.com/aurelia/templating/commit/06be1056d8e44cc301c0a117b26678077b3861c8 which closed a bunch of issues related to `if`.

Please take a look and let me know if this can be closed.

**Comment by Tarpsvo** [comment]
That's weird. The gist you linked still reproduces the same issue.

**Comment by maurice-camp** [comment]
Any update on this issue? I'm still experiencing it with aurelia-binding 1.0.9.
The gist you posted also still has this issue: The value appears to be updating to the value of the original change instead of the value of the last change.

**Comment by spookyvision** [comment]
for what it's worth, I'm having the same problem.

**Comment by thejaff2** [comment]
Also seeing this. My use-case below, isRequesting is true for less than 50ms, gets stuck as true in view. The same also happens when using throttle.

`<loading-indicator loading.one-way="httpClient.isRequesting & debounce:200"></loading-indicator>  `

**Comment by jsobell** [comment]
Sorry, I'm not really involved at the moment, I have too much work to do that's not Aurelia related...

@jdanyow Are you still working on this stuff? This issue need to be re-opened because it's not fixed.

The issue relates to both `show.bind` and `if.bind`, as embedding the bound expression displays the correctly debounced value:
```
<p>Debounced: ${model.nr > 0 & debounce:2000}</p>
```

**Comment by spookyvision** [comment]
still nothing but crickets ... is this really so hard to fix?

**Comment by jsobell** [comment]
@jdanyow , ping!

**Comment by jdanyow** [comment]
Yeah it's a tricky one to fix. I'd recommend not combining `if` and `debounce`. Instead `debounce` the updates to the property the `if` is bound to.

**Comment by spookyvision** [comment]
it appears to me that I'm not using `if`, although I have to admit that a lot of this really flies over my head...

html: `class.bind="chatBubbleClasses & debounce:1000"`

js: 
```
@computedFrom('overview')
    get chatBubbleClasses() {
        const hl = this.overview.has_unread ? 'highlighted ' : '';
        return `${hl} btn btn-default dropdown-toggle btn-jd-menu needsclick`;
    }
```
